version: "3.7"
services:
  db:
   image: postgres:17
   restart: always
   env_file: .env
   environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: ${DB_DATA}
   ports:
      - "${DB_PORT}:${DB_PORT}"
   expose:
      - "${DB_PORT}"
   volumes:
      - postgres-data:${DB_DATA}

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 6379
    expose:
      - 6379

  app:
    build:
      context: .
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db
      - redis

volumes:
  postgres-data: