"""First migration

Revision ID: 5533b298096e
Revises: 
Create Date: 2025-03-28 00:34:31.557522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5533b298096e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('short_code', sa.String(), nullable=False),
    sa.Column('original_link', sa.String(), nullable=False),
    sa.Column('accessed_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_accessed_at'), 'query', ['accessed_at'], unique=False)
    op.create_index(op.f('ix_query_id'), 'query', ['id'], unique=False)
    op.create_index(op.f('ix_query_link_id'), 'query', ['link_id'], unique=False)
    op.create_index(op.f('ix_query_original_link'), 'query', ['original_link'], unique=False)
    op.create_index(op.f('ix_query_short_code'), 'query', ['short_code'], unique=False)
    op.create_index(op.f('ix_query_user_id'), 'query', ['user_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('short_code', sa.String(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_created_at'), 'link', ['created_at'], unique=False)
    op.create_index(op.f('ix_link_id'), 'link', ['id'], unique=False)
    op.create_index(op.f('ix_link_original_url'), 'link', ['original_url'], unique=False)
    op.create_index(op.f('ix_link_short_code'), 'link', ['short_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_short_code'), table_name='link')
    op.drop_index(op.f('ix_link_original_url'), table_name='link')
    op.drop_index(op.f('ix_link_id'), table_name='link')
    op.drop_index(op.f('ix_link_created_at'), table_name='link')
    op.drop_table('link')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_query_user_id'), table_name='query')
    op.drop_index(op.f('ix_query_short_code'), table_name='query')
    op.drop_index(op.f('ix_query_original_link'), table_name='query')
    op.drop_index(op.f('ix_query_link_id'), table_name='query')
    op.drop_index(op.f('ix_query_id'), table_name='query')
    op.drop_index(op.f('ix_query_accessed_at'), table_name='query')
    op.drop_table('query')
    # ### end Alembic commands ###
