"""Second migration

Revision ID: b1bc3261d826
Revises: 5533b298096e
Create Date: 2025-03-28 00:40:49.965600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1bc3261d826'
down_revision: Union[str, None] = '5533b298096e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_premium',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_premium',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
